export const apiRoutes = {
  base: '/api',
  map: '/api/map',
  member: '/api/member',
  coupon: '/api/coupon',
  mission: '/api/mission',
  shop: '/api/shop',
  point: '/api/point',
  admin: '/api/admin',
  events: '/api/events',
  users: '/api/users',
  missions: '/api/missions',
  employees: '/api/employees',
  employee: '/api/employee',
  sites: '/api/sites',
  chargers: '/api/chargers',
  orders: '/api/orders',
  employee_log: '/api/employee_log',
};